### PR TITLE
Generate metadata

### PR DESCRIPTION
**Pull request by shu251**
1.  README documents process to download text files from PANGAEA and ESA
- could only include instructions on how to download ESA text file
- this means that these are downloaded into '/input'
2. jupyter notebook compiles PANGAEA and fastq samples list from ESA to generate *_wenv.txt which are now saved in '/input'
3. then same notebook modifies size fraction range and prints out additional stats on samples (i.e., what depths are included in each 'environmental feature')
4. Summarizes list of ERR fastq file IDs by ocean region and by province within ocean using a script that is customizable. See 21 and 22 for usage. This saves file as 'Samplelist_forassembly.txt'

### CODE REVIEW

**Comment by shu251** [comment]
We can continue discussing how the grouping of samples should go. Here i've chosen to let all samples group by ocean region, but continue splitting to province for: Indian Ocean, N. Atlantic, S. Pacific, and S. Atlantic ("IO", "NAO", "SPO", "SAO").

**Comment by halexand** [comment]
Looking good so far! 

Some things to do: 

- [ ] Make conda env yaml file to run notebook in (that does install of the irkernel)
- [ ] Organize files in folders
- [ ] Add wget command to download the PANGEA file (if it is still too big?)

**Comment by halexand** [comment]
Note: try the install of the conda env as follows: 

`conda env create -f irkernel.yaml --name irkernel`

Then, when you start the jpnotebook you should see that it is an R kernel.

**Comment by halexand** [comment]
alright-- added some changes to the ipynb... and made sure that we don't accidentally push the huge datafiles to the repo (like I just did) via the .gitignore.

**Comment by halexand** [comment]
Hey @shu251 ! I am going to go ahead and merge this branch. Thanks for the awesome script to split or lump the ERRs-- it is great!

Harriet

**Pull request merged**
